version: '3.3'
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: development
    environment:
      - NODE_ENV=development
    volumes:
      - '.:/code'
      - /code/node_modules
    ports:
      - '3000:4000'
    command: yarn watch
