apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reviews-admin-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: reviews-admin
    spec:
      containers:
        - image: gcr.io/co-gcp/reviews-admin
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /reviews-admin/healthcheck
              port: 4000
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
          name: reviews-admin
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /reviews-admin/healthcheck
              port: 4000
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              memory: 256Mi
